version: '3'

tasks:
  install:
    desc: Install dependencies and packages
    aliases: [i]
    cmds:
      - cargo install txtpp --features cli
      - bun i

  dev:
    desc: Run local dev server
    cmds:
    - bunx vitepress dev src --host

  build:
    desc: Build the app locally
    cmds:
    - txtpp verify -r
    - bunx vitepress build src

  serve:
    desc: Serve the built app locally
    cmds:
    - bun serve.ts

  nvim:
    desc: Copy nvim configs from home to repo
    cmds:
    - rm -rf src/public/home/.config/nvim
    - mkdir -p src/public/home/.config/nvim
    # make sure we don't copy the plugins directory
    - cp ~/.config/nvim/init.lua src/public/home/.config/nvim
    - cp -r ~/.config/nvim/after src/public/home/.config/nvim
    - cp -r ~/.config/nvim/lua src/public/home/.config/nvim
    - python nvim.py > src/public/scripts/dl-nvim-config.py

  bash:
    desc: Copy .bashrc from home to repo
    cmds:
    - cp ~/.bashrc src/public/home/.bashrc
    - txtpp -r

  starship:
    desc: Copy starship.toml from home to repo
    cmds:
    - cp ~/.config/starship.toml src/public/home/.config/starship.toml
    - txtpp -r

