version: '3'

tasks:
  install:
    desc: Install dependencies and packages
    aliases: [i]
    cmds:
      - npm i

  dev:
    desc: Run local dev server
    cmds:
    - npx vitepress dev src --host

  build:
    desc: Build the app locally
    cmds:
    - npx vitepress build src

  clean:
    desc: Clean dependencies and temporaries
    cmds:
    - rm -rf node_modules
    - rm -rf src/.vitepress/cache
    - rm -rf src/.vitepress/dist

