version: '3'

tasks:
  install:
    desc: Install dependencies and packages
    aliases: [i]
    cmds:
      - npm i

  dev:
    desc: Run local dev server
    cmds:
    - npx vitepress dev src --host

  build:
    desc: Build the app locally
    cmds:
    - npx vitepress build src

  starship:
    desc: Copy starship.toml from home to repo
    cmds:
    - cp ~/.config/starship.toml src/public/home/.config/starship.toml

