version: '3'

includes:
  mdbook:
    taskfile: mono-dev/task/mdbook.yaml
    optional: true
    internal: true

tasks:
  install-mono:
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1
  install:
    - task: mdbook:install-theme-singlerepo
  dev:
    - mdbook build
    - mdbook watch &
    - live-server book -p 8081

  build:
    desc: Build the app locally
    cmds:
    - pnpm exec vitepress build src

  clean:
    desc: Clean dependencies and temporaries
    cmds:
    - rm -rf node_modules
    - rm -rf src/.vitepress/cache
    - rm -rf src/.vitepress/dist

