# ~/.config/starship.toml
# Use custom format
format = "$shell://$directory$git_branch$git_commit$git_state$git_status $cmake$rust$nodejs$python\n$time$jobs$character"

add_newline = true
command_timeout = 1000
[shell]
disabled = false
powershell_indicator = "\ue70f"
bash_indicator = "\uf303"
cmd_indicator = "\uf489"

[time]
disabled = true
format = "[$time]($style)"
time_format = '%H:%M'

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[jobs]
number_threshold = 1
format = "[\\[$number\\] ]($style)"

[aws]
symbol = "  "

[cmake]
format = "[$symbol($version )]($style)"
symbol = "\ue61d "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncate_to_repo = false
truncation_symbol = ".../"
use_os_path_sep = false
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "

[git_status]
format = "[($ahead_behind)]($style)"
behind = "[\uf433](bold red)"
ahead = "[\uf431](bold green)"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
detect_folders = ["scripts/__pycache__"]

[ruby]
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
