name: Vitepress + Bun CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3
    - name: Setup | Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Setup | Bun Install
      run: bun install --frozen-lockfile
    - name: Build | Build App
      run: bunx vitepress build src
    - name: Build | Upload Artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: src/.vitepress/dist
        retention-days: 3

  deploy:
    name: Deploy
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy | GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
